# Generated by Django 5.0.6 on 2024-05-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
