# Generated by Django 5.0.6 on 2024-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_app', '0004_parent_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
