# Generated by Django 5.0.6 on 2024-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_app', '0005_parent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
