# Generated by Django 5.0.6 on 2024-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_app', '0006_child_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
