# Generated by Django 5.0.6 on 2024-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation_app', '0008_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
